# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['launcher.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('map_cache.png', '.'),
        ('map_meta.json', '.'),
    ],
    hiddenimports=[
        'engine',
        'app',
        'cv2',
        'numpy',
        'scipy',
        'scipy.interpolate',
        'scipy.integrate',
        'scipy.interpolate._fitpack_impl',
        'scipy.interpolate._fitpack',
        'urllib.request',
        'json',
        'base64',
        'io',
        'collections',
        'heapq',
        'ssl',
        'math',
        'time',
        'os',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'tkinter',
        'PyQt5',
        'PySide2',
        'wx',
        'IPython',
        'jupyter',
        'torch',
        'torchvision',
        'torchaudio',
        'sklearn',
        'skimage',
        'pandas',
        'bokeh',
        'dask',
        'distributed',
        'sqlalchemy',
        'tables',
        'h5py',
        'pyarrow',
        'botocore',
        'boto3',
        'sphinx',
        'docutils',
        'pytest',
        'numba',
        'llvmlite',
        'nltk',
        'statsmodels',
        'patsy',
        'openpyxl',
        'xlrd',
        'xlsxwriter',
        'transformers',
        'datasets',
        'tokenizers',
        'sentencepiece',
        'zmq',
        'tornado',
        'markdown',
        'panel',
        'holoviews',
        'datashader',
        'param',
        'pyviz_comms',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='MarineRoutePlanning',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
